fixes to broken steps with new SDK bootstrap terminus script function

diff --git a/script/inc/terminus-init b/script/inc/terminus-init
--- a/script/inc/terminus-init
+++ b/script/inc/terminus-init
@@ -1,5 +1,8 @@
 function _init() {
 
+  echo "Running init"
+  echo "Init installs project runtime dependencies"
+
   shift
   while getopts "b:n:" option; do
      case $option in
@@ -13,27 +16,27 @@ function _init() {
      esac
   done
 
+  if ! [ -x "$(command -v python3)" ]; then
+    echo 'Error: python3 is not installed.' >&2
+    exit 1
+  fi
   if ! [ -x "$(command -v pip)" ]; then
     echo 'Error: pip is not installed.' >&2
     exit 1
   fi
 
-  if ! [ -x "$(command -v python3)" ]; then
-    echo 'Error: python3 is not installed.' >&2
-    exit 1
-  fi
-
-  echo "Installing rust for toml files ..."
+  echo "Installing rust for toml files"
   curl -f -L https://static.rust-lang.org/rustup.sh -O && sh rustup.sh -y > /dev/null 2>&1
   rm rustup.sh
   PATH="$PATH:/root/.cargo/env"
 
-  cd $BASEDIR
-  echo "Removing pycspr requirement ..."
-  awk '!/pycspr/' requirements.txt > temp && mv temp requirements.txt
+  echo "Adding pycspr requirement"
+  cd "$BASEDIR" || exit
 
+  awk '!/pycspr/' requirements.txt > temp && mv temp requirements.txt
   echo "pycspr @ git+https://github.com/casper-network/casper-python-sdk@$BRANCH" >> requirements.txt
 
+  echo "Installing requirements"
   python3 -m pip install -r requirements.txt > /dev/null 2>&1
   python3 -m pip install behave > /dev/null 2>&1
 
